[Java] Do not sign commits when uploading Cluster tutorial to the wiki page as it breaks with an error.
```
 org.eclipse.jgit.api.errors.UnsupportedSigningFormatException: No signer for ssh signatures. Use another signature type for git config gpg.format, or do not sign.
```